language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pipenv run make lint
  - pipenv run make test

# after_success:
#   - export CODECOV_TOKEN=""
#   - bash <(curl -s https://codecov.io/bash)

